version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongo
      - redis
    networks:
      - redforge_net

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - redforge_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - redforge_net

  engine:
    build:
      context: ./engine
    ports:
      - "8000:8000"
    env_file:
      - ./engine/.env
    volumes:
      - ./engine/src:/app/src
    networks:
      - redforge_net

networks:
  redforge_net:

volumes:
  mongo_data:
